version: '3.4'

services:
  pet-bot-server:
    image: pet-bot-server
    build:
      context: ./apps/server
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - pet-bot-net
  pet-bot-web:
    image: pet-bot-web
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - pet-bot-server
    networks:
      - pet-bot-net

networks:
  pet-bot-net:
    driver: bridge